language: objective-c
sudo: false
os: osx
osx_image: beta-xcode6.3

script:
- xcodebuild -showsdks
- instruments -s devices
- xcodebuild -project travis-ios-test.xcodeproj -scheme travis-ios-test -sdk iphonesimulator8.3  -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' test
