language: objective-c
sudo: true
os: osx
osx_image: beta-xcode6.3

script:
- xcodebuild -showsdks
- instruments -s devices
- xcrun simctl list devices
- sudo cat /etc/launchd.conf
- sudo chown $user:wheel /private/tmp
- xcrun simctl boot 81C46931-BFAB-4669-87FC-9E45E4634196
- xcodebuild -project travis-ios-test.xcodeproj -scheme travis-ios-test -destination 'platform=iOS Simulator,name=iPhone 5s,OS=7.1' test
